#!/bin/bash
#propagate_changes

# Copies rules files and scripts from Git repo to system

echo ""
cp -v rules.d/* /etc/udev/rules.d
cp -v bin/* /usr/local/bin
cp dot.kermrc /root/.kermrc
cp showconsoles.cgi /var/www/cgi-bin/
echo ""
[ -e /usr/lib/cgi-bin/ ] && cp *.cgi /usr/lib/cgi-bin/
